In [18]:
import pandas as pd
import numpy as np
from scipy.stats import fisher_exact

In [31]:
all_feedback = pd.read_excel('https://github.com/plau51ble/ThesisChapters/blob/1700ab641690c3ac309c8326d0c5218771ac92eb/Chapter%205/data/AYAC.xlsx')

all_feedback.rename(columns = {'My age':'Age',
                              'My gender':'Gender',
                              'The way smart appliances like connected refrigerator, smart TV, coffee maker, lighting options, smart plugs etc are part of my life:':'Ownership',
                              'I may buy a smart appliance in next':'BuyingPlan',
                              'I trust a specific brand more than others':'Trust',
                              'I already knew about hacking incidents related to a brand':'CompromiseKnowledge',
                              'The security of my network and smart appliances is under my control':'SecurityKnowledge',
                              'CODY had brands of my interest':'Content',
                              'I could understand the intent behind the webpage':'Intent',
                              'I discovered new knowledge about cybersecurity incidents from CODY':'KnowledgeGain',
                              'Information shown in CODY can help in making more informed buying decisions':'BuyingDecision'}, inplace = True)


all_feedback.head()

Timestamp    Age  Gender                    Ownership  \
0 2022-03-21 08:36:01.248  36-45  Female  I own some smart appliances   
1 2022-03-22 07:52:46.354  36-45    Male  I own some smart appliances   
2 2022-03-22 15:08:41.352  18-25  Female  I own some smart appliances   
3 2022-03-22 15:11:46.095  18-25  Female  I own some smart appliances   
4 2022-03-22 16:50:33.882  18-25  Female  I own some smart appliances   

  BuyingPlan  Trust  CompromiseKnowledge  SecurityKnowledge  Content  Intent  \
0    1 month      4                    3                  4      4.0     4.0   
1     1 year      3                    1                  5      4.0     5.0   
2     1 year      5                    3                  4      4.0     3.0   
3    1 month      4                    3                  3      3.0     3.0   
4   3 months      4                    3                  4      4.0     5.0   

   KnowledgeGain  BuyingDecision  
0            4.0             4.0  
1            4.0             5.0  
2            3.0             3.0  
3            4.0             3.0  
4            5.0             5.0

***
## Relationship between Trust in specific brand and existing knowledge of incidents.

In [19]:
aud_feedback = all_feedback[all_feedback['Age'] == "18-25"]

trust_audience = aud_feedback[(aud_feedback['Trust'] >= 4)]
count_trust_knowledge = trust_audience[trust_audience['CompromiseKnowledge'] >= 4].Trust.count()
count_trust_no_knowledge = trust_audience[trust_audience['CompromiseKnowledge'] < 4].Trust.count()
count_trust_no_knowledge

notrust_audience = aud_feedback[(aud_feedback['Trust'] < 3)]
count_notrust_knowledge = notrust_audience[notrust_audience['CompromiseKnowledge'] >= 4].Trust.count()
count_notrust_noknowledge = notrust_audience[notrust_audience['CompromiseKnowledge'] < 4].Trust.count()
count_notrust_noknowledge

table_trust_knowledge = np.array([[count_trust_knowledge, count_trust_no_knowledge], [count_notrust_knowledge, count_notrust_noknowledge]])
table_trust_knowledge

array([[24, 17],
       [ 0,  4]])

In [29]:
# H0: The trust in a specific brand and existing knowledge of compromise history are independent
# H1: The trust in a specific brand and existing knowledge of compromise history are related

oddsr, p = fisher_exact(table_trust_knowledge, alternative='two-sided')
if p <= 0.05:
    # Reject H0
    print ("p-value = ", p, " means:\nThe trust in a specific brand and existing knowledge of compromise history are related with an odds of ", oddsr, ".")
else:
    # Accept H0
    print ("p-value = ", p, " means:\nThe trust in a specific brand and existing knowledge of compromise history are independent.")


p-value =  0.04016913319238926  means:
The trust in a specific brand and existing knowledge of compromise history are related with an odds of  inf .


***
## Relationship between Trust in specific brand and existing knowledge of cybersecurity practices.

In [32]:
aud_feedback = all_feedback[all_feedback['Age'] == "18-25"]

trust_audience = aud_feedback[(aud_feedback['Trust'] >= 4)]
count_trust_secknow = trust_audience[trust_audience['SecurityKnowledge'] >= 4].Trust.count()
count_trust_no_secknow = trust_audience[trust_audience['SecurityKnowledge'] < 4].Trust.count()
count_trust_no_secknow

notrust_audience = aud_feedback[(aud_feedback['Trust'] < 3)]
count_notrust_secknow = notrust_audience[notrust_audience['SecurityKnowledge'] >= 4].Trust.count()
count_notrust_nosecknow = notrust_audience[notrust_audience['SecurityKnowledge'] < 4].Trust.count()
count_notrust_secknow

table_trust_secknow = np.array([[count_trust_secknow, count_trust_no_secknow], [count_notrust_secknow, count_notrust_nosecknow]])
table_trust_secknow

array([[27, 14],
       [ 2,  2]])

In [33]:
# H0: The trust in a specific brand and existing knowledge of cybersecurity practices are independent
# H1: The trust in a specific brand and existing knowledge of cybersecurity practices are related

oddsr, p = fisher_exact(table_trust_secknow, alternative='two-sided')
if p <= 0.05:
    # Reject H0
    print ("p-value = ", p, " means:\nThe trust in a specific brand and existing knowledge of cybersecurity practices are related with an odds of ", oddsr, ".")
else:
    # Accept H0
    print ("p-value = ", p, " means:\nThe trust in a specific brand and existing knowledge of cybersecurity practices are independent.")


p-value =  0.6076109936575044  means:
The trust in a specific brand and existing knowledge of cybersecurity practices are independent.


***
## Relationship between presence of preferred brands in CODY and knowledge discovery by user.

In [34]:
aud_feedback = all_feedback[all_feedback['Age'] == "18-25"]

cody_content = aud_feedback[(aud_feedback['Content'] >= 4)]
count_content_knowgain = cody_content[cody_content['KnowledgeGain'] >= 4].Content.count()
count_content_no_knowgain = cody_content[cody_content['KnowledgeGain'] < 4].Content.count()
count_content_no_knowgain

cody_nocontent = aud_feedback[(aud_feedback['Content'] < 3)]
count_nocontent_knowgain = cody_nocontent[cody_nocontent['KnowledgeGain'] >= 4].Content.count()
count_nocontent_no_knowgain = cody_nocontent[cody_nocontent['KnowledgeGain'] < 4].Content.count()
count_nocontent_no_knowgain

table_content_knowgain = np.array([[count_content_knowgain, count_content_no_knowgain], [count_nocontent_knowgain, count_nocontent_no_knowgain]])
table_content_knowgain

array([[21,  4],
       [ 1,  5]])

In [35]:
# H0: The presence of preferred brands in CODY and knowledge discovery by user are independent
# H1: The presence of preferred brands in CODY and knowledge discovery by user are related

oddsr, p = fisher_exact(table_content_knowgain, alternative='two-sided')
if p <= 0.05:
    # Reject H0
    print ("p-value = ", p, " means:\nThe presence of preferred brands in CODY and knowledge discovery by user are related with an odds of ", oddsr, ".")
else:
    # Accept H0
    print ("p-value = ", p, " means:\nThe presence of preferred brands in CODY and knowledge discovery by user are independent.")


p-value =  0.0038789538233364677  means:
The presence of preferred brands in CODY and knowledge discovery by user are related with an odds of  26.25 .


***
## Relationship between knowledge discovery by user and informed buying decision.

In [36]:
aud_feedback = all_feedback[all_feedback['Age'] == "18-25"]

knowgain = aud_feedback[(aud_feedback['KnowledgeGain'] >= 4)]
count_knowgain_informedbuy = knowgain[knowgain['BuyingDecision'] >= 4].KnowledgeGain.count()
count_knowgain_no_informedbuy = knowgain[knowgain['BuyingDecision'] < 4].KnowledgeGain.count()
count_knowgain_informedbuy

no_knowgain = aud_feedback[(aud_feedback['KnowledgeGain'] < 3)]
count_nogain_informedbuy = no_knowgain[no_knowgain['BuyingDecision'] >= 4].KnowledgeGain.count()
count_nogain_no_informedbuy = no_knowgain[no_knowgain['BuyingDecision'] < 4].KnowledgeGain.count()
count_nogain_no_informedbuy

table_knowgain_informedbuy = np.array([[count_knowgain_informedbuy, count_knowgain_no_informedbuy], [count_nogain_informedbuy, count_nogain_no_informedbuy]])
table_knowgain_informedbuy

array([[26,  3],
       [ 0,  3]])

In [37]:
# H0: The knowledge discovery by user and informed buying behavior are independent
# H1: The knowledge discovery by user and informed buying behavior are related

oddsr, p = fisher_exact(table_knowgain_informedbuy, alternative='two-sided')
if p <= 0.05:
    # Reject H0
    print ("p-value = ", p, " means:\nThe knowledge discovery by user and informed buying behavior are related with an odds of ", oddsr, ".")
else:
    # Accept H0
    print ("p-value = ", p, " means:\nThe knowledge discovery by user and informed buying behavior are independent.")


p-value =  0.0040322580645161315  means:
The knowledge discovery by user and informed buying behavior are related with an odds of  inf .
